name: Bug Report
description: Report a bug or issue
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the issue?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. 
        2. 
        3.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g., 1.0.0
